### ISSUE TITLE
critical crash when adding hundreds / thousands of spots

### ISSUE THREAD

**Issue by johndpope** [DDRBoxman/google-maps-ios-utils#14]
for (int i = 0; i < 15000; i++) {
Spot *spot = [self generateSpot];
[clusterManager_ addItem:spot];
}

load the map - zoom in and zoom in - zoom in - then crash

3c2f48544d4c3e0a}}
2015-04-09 20:04:44.249 Google Maps iOS Example18021:4013799 was false: Reached the max number of texture atlases, can not allocate more.

**Comment by johndpope** [comment]
I think we need to adjust logic to only draw the pins if they are inside the viewable screen and remove the ones not on screen. 

- (void)mapView:(GMSMapView *)mapView_ didChangeCameraPosition:(GMSCameraPosition *)position {
    [NSObject cancelPreviousPerformRequestsWithTarget:self
                                             selector:@selector(find) object:nil];
    [self performSelector:@selector(find) withObject:nil afterDelay:0.2];
}

**Comment by kyramckenna** [comment]
This is great John...thank you for sharing!

**Comment by pkarc** [comment]
Nice Job, Thank you

**Comment by johndpope** [comment]
hey @kyramckenna  / @pkarc  - doing spring cleaning on old github tickets.
 They say - when you clean / you clean your mind. 
149 to go.
