### ISSUE TITLE
How to select marker on map?

### ISSUE THREAD

**Issue by Chiliec** [DDRBoxman/google-maps-ios-utils#25]
Before I use this solution, I do it with that code:
~~~swift
var marker: GMSMarker!
for rink in rinks {
    marker = GMSMarker()
    ...
}
if rinks.count == 1 {
    self.map.selectedMarker = marker // this string
}
~~~
Now it doesn't work. Please, promt me how to do it coupled with clusterManager.

**Comment by chiliec** [comment]
Decided by non-clustering if have only one marker.
