### ISSUE TITLE
Tapping on a cluster vs tapping on a marker

### ISSUE THREAD

**Issue by christophernassar** [DDRBoxman/google-maps-ios-utils#27]
How do we detect the difference between tapping on a cluster or a market in - (BOOL)mapView:(GMSMapView *)mapView didTapMarker:(GMSMarker *)marker

**Comment by OMK265** [comment]
I am also facing same issue. So please help me out on this.

**Comment by OMK265** [comment]
@DDRBoxman @christophernassar   Please help me on it.

**Comment by christophernassar** [comment]
> - (BOOL)mapView:(GMSMapView *)mapView didTapMarker:(CustomGMSMarker *)marker {
>   [self resignResponder];
>   
>   if(marker.count > 1){
>       NSLog(@"cluster tapped");
>   } else {
>       NSLog(@"simple marker tapped");
>   }
>   
>   return YES;
>   }

//Remember you need to customize your GMSMarker and insert the number of markers into the clusters in order to differentiate between them later like in this case

**Comment by OMK265** [comment]
Thanks a lot.

Can you please help me out solving one more issue. I have already opened a issue for the same.
Unable to Show Pins when on Same Location while clustering #28

**Comment by OMK265** [comment]
i am Still Waiting for your reply
Unable to Show Pins when on Same Location while clustering #28
