### ISSUE TITLE
Support for didTapMarker

### ISSUE THREAD

**Issue by cspnanda** [DDRBoxman/google-maps-ios-utils#9]
After I set the delegate of GMSmapView to cluserManager, there is no way to access to methods like 

   -(BOOL) mapView:(GMSMapView *)mapView didTapMarker:(GMSMarker *)marker

which are GMSmapViewDelegate. Now if I tap on the marker, the method doesn't get called. Please add this.

**Comment by norman784** [comment]
hey @cspnanda  check it out, I just [implemented the delegates](https://github.com/DDRBoxman/google-maps-ios-utils/pull/11), its a bit late  but maybe it still useful for you
